# Generated by Django 2.1.7 on 2019-03-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RightWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=128, unique=True, verbose_name='Word')),
            ],
            options={
                'verbose_name': 'Right words',
            },
        ),
        migrations.CreateModel(
            name='WrongWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=128, unique=True, verbose_name='Word')),
            ],
            options={
                'verbose_name': 'Wrong words',
            },
        ),
    ]
