# Generated by Django 2.1.7 on 2019-03-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spell_checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightwords',
            name='first_letter',
            field=models.CharField(blank=True, db_index=True, default='', help_text='its for custom index', max_length=1, verbose_name='First letter'),
        ),
        migrations.AddField(
            model_name='rightwords',
            name='length',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='its for custom index', verbose_name='First letter'),
        ),
    ]
